// <auto-generated />
namespace Sabio.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class C7Init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(C7Init));
        
        string IMigrationMetadata.Id
        {
            get { return "201503111914257_C7Init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
